import type { Metadata } from "next";
import { outfit } from "./ui/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased flex justify-center select-none p-4 sm:p-0`}>
        {children}
      </body>
    </html>
  );
}
